//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIOS
    {
        public decimal ID_ANUNCIO { get; set; }
        public Nullable<decimal> ID_CONDOMINIO { get; set; }
        public string TITULO { get; set; }
        public string CUERPO { get; set; }
        public string REMITENTE { get; set; }
        public Nullable<System.DateTime> FECHA_ANUNCIO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
    }
}
