//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDOMINIO
    {
        public CONDOMINIO()
        {
            this.ANUNCIOS = new HashSet<ANUNCIOS>();
            this.ESPACIOS_COMUNES = new HashSet<ESPACIOS_COMUNES>();
            this.LIBRO_SUCESOS = new HashSet<LIBRO_SUCESOS>();
            this.USUARIO_X_CONDOMINIO = new HashSet<USUARIO_X_CONDOMINIO>();
            this.VIVIENDA = new HashSet<VIVIENDA>();
        }
    
        public decimal ID_CONDOMINIO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> NUMERO_DIRECCION { get; set; }
        public Nullable<decimal> ID_COMUNA { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
    
        public virtual ICollection<ANUNCIOS> ANUNCIOS { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<ESPACIOS_COMUNES> ESPACIOS_COMUNES { get; set; }
        public virtual ICollection<LIBRO_SUCESOS> LIBRO_SUCESOS { get; set; }
        public virtual ICollection<USUARIO_X_CONDOMINIO> USUARIO_X_CONDOMINIO { get; set; }
        public virtual ICollection<VIVIENDA> VIVIENDA { get; set; }
    }
}
