//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public PAGO()
        {
            this.PAGOXGASTO = new HashSet<PAGOXGASTO>();
        }
    
        public decimal ID_PAGO { get; set; }
        public Nullable<decimal> ID_TIPO_PAGO { get; set; }
        public Nullable<decimal> MONTO_PAGO { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
        public virtual ICollection<PAGOXGASTO> PAGOXGASTO { get; set; }
    }
}
