//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public Nullable<decimal> ID_VIVIENDA { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVADA { get; set; }
        public Nullable<decimal> ID_ESPACIO { get; set; }
        public string ESTADO_RESERVA { get; set; }
    
        public virtual ESPACIOS_COMUNES ESPACIOS_COMUNES { get; set; }
        public virtual VIVIENDA VIVIENDA { get; set; }
    }
}
