//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENTE
    {
        public decimal ID_RESIDENTE { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> ID_VIVIENDA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual VIVIENDA VIVIENDA { get; set; }
    }
}
