//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_GASTO
    {
        public TIPO_GASTO()
        {
            this.GASTO = new HashSet<GASTO>();
        }
    
        public decimal ID_TIPO_GASTO { get; set; }
        public string DESCRPCION { get; set; }
    
        public virtual ICollection<GASTO> GASTO { get; set; }
    }
}
