//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_X_CONDOMINIO
    {
        public decimal ID_UXC { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<decimal> ID_CONDOMINIO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
