//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.USUARIO_X_CONDOMINIO = new HashSet<USUARIO_X_CONDOMINIO>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public Nullable<decimal> ID_TIPO_USUARIO { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public string CLAVE { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_X_CONDOMINIO> USUARIO_X_CONDOMINIO { get; set; }
    }
}
