//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigescoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIVIENDA
    {
        public VIVIENDA()
        {
            this.GASTO = new HashSet<GASTO>();
            this.RESERVA = new HashSet<RESERVA>();
            this.RESIDENTE = new HashSet<RESIDENTE>();
        }
    
        public decimal ID_VIVIENDA { get; set; }
        public Nullable<decimal> ID_CONDOMINIO { get; set; }
        public string NUMERO { get; set; }
        public string NOMBRE_CALLE { get; set; }
        public string PLANTA_UBICACION { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual ICollection<GASTO> GASTO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<RESIDENTE> RESIDENTE { get; set; }
    }
}
